@startuml
actor SalesClerk as adm
participant "//<<presentation>>//\nDefineNewCategoryUI" as ui

autonumber

adm-->ui: Define new category

activate ui

ui-->adm: asks user information

adm-->ui: Code, Description

ui-->adm: displayCategoryInfo

deactivate ui
@enduml