@startuml Modelo de domínio
skinparam style strictuml
skinparam DefaultFontName Arial
skinparam DefaultFontSize 13
skinparam ArrowThickness 1.5
skinparam Arrowcolor #gray
hide empty members

Cliente -left--|> Utilizador
Empregado --|> Utilizador
SalesClerk -up--|> Utilizador
SalesManager -right--|> Utilizador
Produto "*"-"1" Categoria : pertence >
Cliente "1"-"1" Carrinho : possui >
Carrinho "1"-up-"*" Pedido : contém >
Pedido "*"-left-"1" Produto : contém >
Cliente "1"-down-"*" Encomenda : realiza >
Encomenda "*"-"1" Estado : possui >
Armazem "1"-up-"*" Produto : armazena >
Inquérito "*"-"*" Questão : contém >
Armazem "1"-"*" AGV : possui >
Cliente "1"-up-"1" Inquérito: responde >


class "Produto" as Produto {
código
descrição curta
descrição extensa
descriçã técnica
referência
código de barras
código de produção
marca
conjuntoFotos
preço com taxa
preço sem taxa
}

class "Categoria" as Categoria {
código
descrição
}


class "Cliente" as Cliente {
nif
email
númeroTelemóvel
dataNascimento
género
endereçoFaturação
endereçoExpedição
}

class "Carrinho" as Carrinho {
idCarrinho
}

class "Pedido" as Pedido {
quantidade
idEncomenda
}

class "Encomenda" as Encomenda {
idEncomenda
dataRegisto
métodoPagamento
}

class "Estado" as Estado {
idEstado
descrição
}

class "Armazem" as Armazem{
idArmazem
}

class AGV{
idAGV
descrição
modelo
peso máximo
localização base
autonomia atual
tarefa atual
}

class "Empregado de Armazem" as Empregado{
}

class "SalesClerk" as SalesClerk{
}

class "Sales Manager" as SalesManager{
}

class "Inquérito" as Inquérito{
idInquerito
}

class "Questão" as Questão{
id
tipo
descricao
}

class "Utilizador" as Utilizador{
idUtilizador
nome
}


@enduml