@startuml

skinparam linetype ortho

entity Warehouse
entity Aisle
entity Section
entity Shelf
object AisleIdentifer
object AisleLocation
object RowIdentifier
object RowLocation
object ShelfIdentifier
object ShelfLocation




Warehouse "1" --> "1..*" Aisle : organized by
Aisle "1" --> "1..*" Section : divided by
Section "1" --> "1..*" Shelf  : contains
Aisle --> AisleIdentifer
Aisle --> AisleLocation
Section --> RowIdentifier
Section --> RowLocation
Shelf --> ShelfIdentifier
Shelf --> ShelfLocation



@enduml