@startuml Modelo de domínio
' hide the spot


' avoid problems with angled crows feet
skinparam linetype ortho

entity Customer
entity User
enum WarehouseEmployee
enum SalesClerk
enum SalesManager
enum Admin
object VAT
object Email
object PhoneNumber
object Birthday
object Gender
object DeliveringPostalAddresses
object BillingPostalAddresses
Customer --> VAT
Customer --> Email
Customer --> PhoneNumber
Customer --> Birthday
Customer --> Gender
Customer --> DeliveringPostalAddresses
Customer --> BillingPostalAddresses

object User_id
object Name
User --> User_id
User --> Name

Customer -left--|> User
WarehouseEmployee --|> User
SalesClerk -up--|> User
SalesManager -right--|> User
Admin -right--|> User

@enduml