@startuml

skinparam linetype ortho

entity AGV
object AGVIdentifier
object AGVShortDescription
object Model
object MaximumWeight
object Autonomy
object Task
object Volume


AGV --> AGVIdentifier
AGV --> AGVShortDescription
AGV --> Model
AGV --> MaximumWeight
AGV --> Autonomy
AGV --> Task
AGV --> Volume

@enduml