@startuml

skinparam linetype ortho

entity Warehouse
entity Aisle
entity Row
entity Shelf
object AisleIdentifer
object AisleLocation
object RowIdentifier
object RowLocation
object ShelfIdentifier
object ShelfLocation




Warehouse "1" --> "1..*" Aisle : organized by
Aisle "1" --> "1..*" Row : divided by
Row "1" --> "1..*" Shelf  : contains
Aisle --> AisleIdentifer
Aisle --> AisleLocation
Row --> RowIdentifier
Row --> RowLocation
Shelf --> ShelfIdentifier
Shelf --> ShelfLocation



@enduml